### ISSUE TITLE
k3s打开traefik的dashboard的记录

### ISSUE THREAD

**Issue by damingerdai** [damingerdai/damingerdai.github.io#1]
# 开启dashboard

在`/var/lib/rancher/k3s/server/manifests`中创建*traefik-config.yaml*：

```yaml
apiVersion: helm.cattle.io/v1
kind: HelmChartConfig
metadata:
  name: traefik
  namespace: kube-system
spec:
  valuesContent: |-
    dashboard:
      enabled: true
      domain: "www.damingerdai.com"
```

# 端口转发

```bash
kubectl -n kube-system port-forward --address 0.0.0.0 $(kubectl -n kube-system get pods --selector "app.kubernetes.io/name=traefik" --output=name) 9000:9000
```
